# Generated by Django 5.2.12 on 2026-03-13 21:49

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        ("consoles", "0001_initial"),
        ("genres", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Games",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("release_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("consoles", models.ManyToManyField(blank=True, related_name="games", to="consoles.consoles")),
                (
                    "developer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="developed_games",
                        to="companies.companies",
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="games",
                        to="genres.genres",
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_games",
                        to="companies.companies",
                    ),
                ),
            ],
            options={
                "verbose_name": "game",
                "db_table": "games",
                "ordering": ["name"],
            },
        ),
    ]
