# Generated by Django 5.2.12 on 2026-03-17 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_games_description_en_games_description_es_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='cover_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
