# Generated by Django 5.2.12 on 2026-03-18 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("franchises", "0001_initial"),
        ("games", "0003_games_cover_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="games",
            name="franchise",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="games",
                to="franchises.franchises",
            ),
        ),
    ]
