# Generated by Django 5.2.12 on 2026-03-18 10:28

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Franchises",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=200)),
                ("name_en", models.CharField(max_length=200, null=True)),
                ("name_es", models.CharField(max_length=200, null=True)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("description_en", models.TextField(blank=True, default="", null=True)),
                ("description_es", models.TextField(blank=True, default="", null=True)),
                ("founded_year", models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "franchise",
                "verbose_name_plural": "franchises",
                "db_table": "franchises",
                "ordering": ["name"],
            },
        ),
    ]
