# Generated by Django 5.2.12 on 2026-03-13 21:49

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Companies",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("country", models.CharField(blank=True, default="", max_length=100)),
                ("founded", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("website", models.URLField(blank=True, default="")),
            ],
            options={
                "verbose_name": "company",
                "verbose_name_plural": "companies",
                "db_table": "companies",
                "ordering": ["name"],
            },
        ),
    ]
