# Generated by Django 5.2.12 on 2026-03-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='name_en',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='name_es',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
