# Generated by Django 5.2.12 on 2026-03-14 10:36

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("consoles", "0002_consoles_name_en_consoles_name_es"),
        ("games", "0002_games_description_en_games_description_es_and_more"),
        ("regions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Releases",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("active", models.BooleanField(default=True)),
                ("release_date", models.DateField(blank=True, null=True)),
                (
                    "console",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="releases",
                        to="consoles.consoles",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="releases", to="games.games"
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="releases", to="regions.regions"
                    ),
                ),
            ],
            options={
                "verbose_name": "release",
                "db_table": "releases",
                "ordering": ["release_date"],
                "unique_together": {("game", "region", "console")},
            },
        ),
    ]
